server:
  port: 8088

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  auto-renew: true
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # jwt秘钥
  jwt-secret-key: asdasdasifhueuiwyurfewbfjsdafjk

#sql配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa_fcfz?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

    # 文件上传配置
  servlet:
    multipart:
#      location: D:\mytmp\upload
      # 设置单个文件上传大小
      max-file-size: 10MB
      max-request-size: 20MB

my:
  files:
    upload:
      path: D:\Projects\WeSpace\WeOfficeSys\OA\src\main\resources\file\